apply plugin: 'com.android.application'

android {
    namespace "com.Mohammad.ac.test3g"
    compileSdkVersion 34
    
    defaultConfig {
        applicationId 'com.Mohammad.ac.SpeedTest'
        minSdkVersion 21
        targetSdkVersion 34
        versionName '2.40'
        versionCode 240
    }

    signingConfigs {
        debug {
            storeFile file('C:/Users/hp2/.android/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.cardiomood.android:android-widgets:0.1.1'
    implementation files('libs/volley.jar')
    implementation 'fr.bmartel:jspeedtest:1.25'
}
